export const projects = [
  {
    id: 1,
    title: "Santiago Bernabéu",
    description: "Digital Blueprinting, 3D Visualization, Construction Planning",
    image: "/projects/project1.jpg",
    column: 1,
  },
  {
    id: 2,
    title: "Camp Nou",
    description: "Virtual Reality Tours, BIM Modeling, Structural Analysis",
    image: "/projects/project2.jpg",
    column: 1,
  },
  {
    id: 3,
    title: "Old Trafford",
    description: "Architectural Rendering, Interior Visualization, 3D Mapping",
    image: "/projects/project3.jpg",
    column: 1,
  },
  {
    id: 4,
    title: "Allianz Arena",
    description: "Parametric Design, Environmental Simulation, Light Studies",
    image: "/projects/project4.jpg",
    column: 1,
  },
  {
    id: 5,
    title: "Anfield",
    description: "AR/VR Experience Design, Interactive Walkthroughs, Fan Zones",
    image: "/projects/project5.jpg",
    column: 2,
  },
  {
    id: 6,
    title: "San Siro",
    description: "Acoustic Modeling, Crowd Flow Simulation, Safety Analysis",
    image: "/projects/project6.jpg",
    column: 2,
  },
  {
    id: 7,
    title: "Wembley Stadium",
    description: "Digital Twin Creation, IoT Integration, Smart Stadium Design",
    image: "/projects/project7.jpg",
    column: 2,
  },
  {
    id: 8,
    title: "Signal Iduna Park",
    description: "Sustainability Analysis, Green Building Design, Energy Modeling",
    image: "/projects/project8.jpg",
    column: 2,
  },
];
