export const projects = [
  {
    id: 1,
    title: "Authentic Brand Stories",
    description: "Brand Strategy, Creative Direction, Content Production",
    image: "/projects/project1.jpg",
    column: 1,
  },
  {
    id: 2,
    title: "Cultural Narratives",
    description: "Cultural Insights, Strategy Development, Brand Activation",
    image: "/projects/project2.jpg",
    column: 1,
  },
  {
    id: 3,
    title: "Digital Experiences",
    description: "UX/UI Design, Web Development, Interactive Media",
    image: "/projects/project3.jpg",
    column: 1,
  },
  {
    id: 4,
    title: "Content Creation",
    description: "Photography, Videography, Social Media Content",
    image: "/projects/project4.jpg",
    column: 1,
  },
  {
    id: 5,
    title: "Influencer Campaigns",
    description: "Talent Sourcing, Campaign Strategy, Content Production",
    image: "/projects/project5.jpg",
    column: 2,
  },
  {
    id: 6,
    title: "Brand Development",
    description: "Visual Identity, Brand Guidelines, Marketing Collateral",
    image: "/projects/project6.jpg",
    column: 2,
  },
  {
    id: 7,
    title: "Social Media Strategy",
    description: "Platform Strategy, Content Calendar, Community Management",
    image: "/projects/project7.jpg",
    column: 2,
  },
  {
    id: 8,
    title: "Event Experiences",
    description: "Event Design, Production Management, Brand Activation",
    image: "/projects/project8.jpg",
    column: 2,
  },
];
